### ISSUE TITLE
Headless rendering support.

### ISSUE THREAD

**Issue by Stelrin** [riadhe/Qeen#1]
GLFW does not initialize in a headless environment, support for that is required for CLI server deployment.

```java
2019-10-01T13:49:06.977194+00:00 app[run.1]: [LWJGL] GLFW_PLATFORM_ERROR error
2019-10-01T13:49:06.977276+00:00 app[run.1]: Description : X11: The DISPLAY environment variable is missing
2019-10-01T13:49:06.977302+00:00 app[run.1]: Stacktrace  :
2019-10-01T13:49:06.97756+00:00 app[run.1]: org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:830)
2019-10-01T13:49:06.97761+00:00 app[run.1]: com.riadhe.qeen.Qeen.lambda$new$0(Qeen.java:75)
2019-10-01T13:49:06.977659+00:00 app[run.1]: java.lang.Thread.run(Thread.java:748)
2019-10-01T13:49:06.97866+00:00 app[run.1]: Exception in thread "Thread-0" java.lang.IllegalStateException: Failed to initialize GLFW!
2019-10-01T13:49:06.978736+00:00 app[run.1]: at com.riadhe.qeen.Qeen.lambda$new$0(Qeen.java:75)
2019-10-01T13:49:06.978815+00:00 app[run.1]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by riadhe** [comment]
GLFW does **not** support headless rendering (systems without X).
Creating a display using the X virtual frame buffer (Xvfb) might solve the issue.
